# version: '3'
# services:
#   postgres:
#     container_name: postgres_sub
#     image: postgres:latest
#     ports:
#       - '5434:5432'
#     volumes:
#       - /data/postgres:/data/postgres
#     env_file:
#       - docker.env
#     networks:
#       - postgres

#   pgadmin:
#     links:
#       - postgres:postgres
#     container_name: pgadmin_sub
#     image: dpage/pgadmin4
#     ports:
#       - '8000:80'
#     volumes:
#       - /data/pgadmin:/root/.pgadmin
#     env_file:
#       - docker.env
#     networks:
#       - postgres

# networks:
#   postgres:
#     driver: bridge
